apiVersion: v1
kind: Service
metadata:
  name: redpanda
  labels:
    {{- include "redpanda.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # redpanda admin http
    - port: 9000
      targetPort: 9644
      protocol: TCP
    # redpanda api
    - port: 9001
      targetPort: 9092
      protocol: TCP
  selector:
    {{- include "redpanda.selectorLabels" . | nindent 4 }}
