apiVersion: v1
kind: Service
metadata:
  name: redpanda
  labels:
    {{- include "redpanda.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # redpanda api
    - port: {{ .Values.externalPort2 }}
      targetPort: 9092
      protocol: TCP
      name: api
  selector:
    {{- include "redpanda.selectorLabels" . | nindent 4 }}
